### ISSUE TITLE
Identity without IDENTITY_ADMIN permission cannot update identity

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-identity-rest#5]
In order to update key preferences in particular, an identity needs to be able to update an identity by way of this code path:

https://github.com/digitalbazaar/bedrock-identity-rest/blob/master/lib/services.identity.js#L643

However, the `setRoles` function:
https://github.com/digitalbazaar/bedrock-identity-rest/blob/master/lib/services.identity.js#L669

requires IDENTITY_ADMIN permission: https://github.com/digitalbazaar/bedrock-identity/blob/master/lib/identity.js#L300

The permission requirement is proper, since only an admin should be able to change roles.  However, when `setRoles` fails due to a permission denied error, the entire update operation is aborted.

The solution for this should be to specifically ignore a permission denied error returned from `setRoles` and proceed with the remainder of the update operation.

**Comment by dlongley** [comment]
> However, when setRoles fails due to a permission denied error, the entire update operation is aborted.

I think this is correct behavior. This is a `PATCH` operation -- if the whole thing doesn't work, it should fail. Someone shouldn't be trying to set roles _and_ update the identity at once unless they can actually do both of those things.

It sounds like this may be a bug with how the call is being made -- and the roles should be left out if the intention is to just update the identity itself.

**Comment by dlongley** [comment]
Closed by fixing frontend.
